config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'site#index'
  get 'dashboard' => 'dashboard#index'
  resources :samples
  get 'towers' => 'samples#towers'
  resources :reports
  get 'data/:id' => 'reports#data'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :towers
  has_many :samples
  belongs_to :user
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :tower
  belongs_to :company

  def as_json(options={})
    options[:methods] = [:cycles_of_concentration,:formatted_sample_date]
    super
  end

  def cycles_of_concentration
    sodium % city_sodium
  end

  def formatted_sample_date
    sample_date.strftime('%Y-%m-%d')
  end


end

app/models/tower.rb
class Tower < ActiveRecord::Base
  belongs_to :company
  has_many :samples

  def self.by_company(user)
    where('company_id =  ?', user.company_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
      '/dashboard'
  end

  def after_sign_up_path_for(resource)
    '/dashboard'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  def index
    @towers = Tower.by_company current_user
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    tower = Tower.find(params['id'])
    @data = tower.samples.order( 'samples.sample_date ASC' )
  end

  def data
    tower = Tower.find(params['id'])
    @data = tower.samples.order( 'samples.sample_date ASC' )
    render json: @data
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @samples = Sample.all
  end

  def new
    @sample = Sample.new
  end

  def create
    @sample = Sample.new sample_params
    if @sample.save
      redirect_to samples_path
    else
      render :action => 'new'
    end
  end

  def edit
    @sample = Sample.find params[:id]
  end

  def update
    @sample = Sample.find params[:id]
    if @sample.update_attributes sample_params
      redirect_to samples_path
    else
      render :action => :edit
    end
  end

  def destroy
    @sample = Sample.find params[:id]
    @sample.destroy
    redirect_to samples_path
  end

  def show
    @sample = Sample.find params[:id]
  end

  def towers
    towers = Tower.where(company_id:params['company'])
    render json: towers
  end

  private

  def sample_params
    params.require(:sample).permit(:user, :tower_id, :company_id, :sample_date, :city_sodium, :date, :conductivity, :ph, :magnesium, :calcium, :ca_mg_ratio, :iron, :copper, :phosphorus,
    :zinc, :sodium, :molybdate, :silicate, :boron, :aluminum, :sulfer, :manganese, :total_hardness, :ortho_po4, :azole, :polymer, :free_chlorine)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<% if current_user.is_admin %>
<div>
  <h2>Admin</h2>
  <%= link_to "Samples Editor", samples_path %>
  <br>
  Tower Editor
  <br>
  Company Editor
  <br>
  User Editor
</div>
<% elsif !current_user.is_admin %>
<div>
  <h2>Tower Manager</h2>
  <table border="1">
    <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Type</th>
      <th>Health</th>
      <th>Options</th>
    </tr>
    </thead>
    <% @towers.each do |tower| %>
      <tr>
        <td><%= tower.id %></td>
        <td><%= tower.name %></td>
        <td><%= tower.tower_type %></td>
        <td></td>
        <td><%= link_to 'Reports', report_path(tower.id) %></td>
      </tr>
  <% end -%>
  </table>
</div>
<% end %>
<div>

</div>

app/views/layouts/application.html.erb
<html>
<head>
  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= favicon_link_tag 'favicon-flask.ico' %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.6.0/metricsgraphics.min.js" charset="utf-8"></script>
</head>
<body>
<nav class="navbar-app navbar-shrink">
  <div class="container">
    <div>
      <a class="navbar-brand" href="/">YourCoolingTower</a>
    </div>
    <div class="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <a href="/"><%= current_user.email %></a>
          <% end %>
        <li>
          <% if user_signed_in? %>
            <a href="/users/sign_out">Logout</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="content">
  <%= yield %>
</div>
</body>
</html>

app/views/purchase/index.html.erb
credit card form

<%= form_tag receipt_path do %>
    <%= label_tag :cc_name, 'Credit Card Name' %><br>
    <%= text_field_tag :cc_name, '' %><br>
    <%= label_tag :cc_num, 'Credit Card Number' %><br>
    <%= text_field_tag :cc_num, '' %><br>
    <%= submit_tag 'Submit' %>
<% end %>

app/views/purchase/receipt.html.erb
Thank you for your odor

app/views/reports/show.html.erb
<h2>Tower Analysis</h2>
<!--<table border="1">-->
  <!--<thead>-->
  <!--<tr>-->
    <!--<th>Sample Date</th>-->
    <!--<th>Conductivity</th>-->
    <!--<th>COC</th>-->
    <!--<th>Free Chlorine</th>-->
    <!--<th>Polymer</th>-->
  <!--</tr>-->
  <!--</thead>-->
<!--<% @data.each do |data| %>-->
    <!--<tr>-->
      <!--<td><%= data.sample_date.strftime('%m/%d/%Y') %></td>-->
      <!--<td><%= data.conductivity %></td>-->
      <!--<td><%= data.cycles_of_concentration %></td>-->
      <!--<td><%= data.free_chlorine %></td>-->
      <!--<td><%= data.polymer %></td>-->
    <!--</tr>-->
<!--<% end -%>-->
<!--</table>-->
<div id="conductivity"></div>
<div id="coc"></div>
<div id="free-chlorine"></div>
<div id="polymer"></div>
<script>
    d3.json('/data/<%= params['id'] %>', function(data) {
    data = MG.convert.date(data, 'formatted_sample_date');
    MG.data_graphic({
        title: "Conductivity",
        description: "The concentration of dissolved solids which have been ionized in a polar solution such as water.",
        data: data,
        area: false,
        interpolate: 'basic',
        width: 800,
        height: 200,
        right: 40,
        max_y: 900,
        min_y: 800,
        target:'div#conductivity',
        x_accessor: 'formatted_sample_date',
        y_accessor: 'conductivity'
    });
});
d3.json('/data/<%= params['id'] %>', function(data) {
    data = MG.convert.date(data, 'formatted_sample_date');
    MG.data_graphic({
        title: "Cycles of Concentration",
        description: "The number of times the dissolved minerals in the system cooling water are concentrated versus the level in the raw makeup water.",
        data: data,
        area: false,
        interpolate: 'basic',
        width: 800,
        height: 200,
        right: 40,
        max_y: 17,
        min_y: 7,
        target:'div#coc',
        x_accessor: 'formatted_sample_date',
        y_accessor: 'cycles_of_concentration'
    });
});
    d3.json('/data/<%= params['id'] %>', function(data) {
    data = MG.convert.date(data, 'formatted_sample_date');
    MG.data_graphic({
        title: "Free Chlorine",
        description: "The concentration of residual chlorine in water which is present as dissolved gas (Cl2), hypochlorous acid (HOCl), and/or hypochlorite ion (OCl-).",
        data: data,
        area: false,
        interpolate: 'basic',
        width: 800,
        height: 200,
        right: 40,
        max_y: 3,
        min_y: 0,
        target:'div#free-chlorine',
        x_accessor: 'formatted_sample_date',
        y_accessor: 'free_chlorine'
    });
});
    d3.json('/data/<%= params['id'] %>', function(data) {
    data = MG.convert.date(data, 'formatted_sample_date');
    MG.data_graphic({
        title: "Polymer",
        description: "The amount of scale inhibitors present.",
        data: data,
        area: false,
        interpolate: 'basic',
        width: 800,
        height: 200,
        right: 40,
        max_y: 350,
        min_y: 250,
        target:'div#polymer',
        x_accessor: 'formatted_sample_date',
        y_accessor: 'polymer'
    });
});
</script>

app/views/samples/_form.html.erb
<%= form_for @sample do |sample| %>
    <div class="form-group">
      <%= sample.label :company, "Company Name" %><br>
      <%= sample.collection_select(:company_id, Company.all, :id, :name, :prompt => 'Select') %>
    </div>
    <div class="form-group">
      <%= sample.label :tower, "Cooling Tower Name" %><br>
      <%= sample.collection_select(:tower_id, Tower.all, :id, :name, :prompt => 'Select') %>
    </div>
    <hr>
    <div class="form-group">
      <%= sample.label :sample_date, "Sample Date" %>
      <%= sample.date_field :sample_date,{class: 'datepicker'}  %>
    </div>
    <hr>
    <h4>City Water Data</h4>
    <div class="form-group">
      <%= sample.label :city_sodium, "Sodium (as ppm Na)" %>
      <%= sample.number_field :city_sodium, {class: 'form-control', step: 'any', placeholder: 'City Sodium'}  %>
    </div>
    <hr>
    <h4>Cooling Tower Data</h4>
    <div class="form-group">
      <%= sample.label :conductivity, "Conductivity" %>
      <%= sample.number_field :conductivity,{class: 'form-control',  step: 'any', placeholder: 'Conductivity'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :ph, "pH" %>
      <%= sample.number_field :ph, {class: 'form-control', step: 'any', placeholder: 'ph'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :magnesium, "Magnesium (as ppm CaCO3)" %>
      <%= sample.number_field :magnesium, {class: 'form-control', step: 'any' ,placeholder: 'Magnesium'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :calcium, "Calcium (as ppm CaCO3)" %>
      <%= sample.number_field :ph, {class: 'form-control', step: 'any',placeholder: 'Calcium'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :ca_mg_ratio, "CA/MG_Ratio" %>
      <%= sample.number_field :ca_mg_ratio, {class: 'form-control', step: 'any', placeholder: 'CA/MG_Ratio'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :iron, "Iron (as ppm Fe)" %>
      <%= sample.number_field :iron, {class: 'form-control', step: 'any' ,placeholder: 'Iron'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :copper, "Copper (as ppm Cu)" %>
      <%= sample.number_field :copper, {class: 'form-control', step: 'any' ,placeholder: 'Copper'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :phosphorus, "Phosphorus (as ppm PO4)" %>
      <%= sample.number_field :phosphorus, {class: 'form-control', step: 'any' ,placeholder: 'Phosphorus'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :zinc, "Zinc (as ppm PO4)" %>
      <%= sample.number_field :zinc, {class: 'form-control', step: 'any', placeholder: 'Zinc'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :sodium, "Sodium (as ppm Na)" %>
      <%= sample.number_field :sodium, {class: 'form-control', step: 'any', placeholder: 'Sodium'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :molybdate, "Molybdate (as ppm Mo)" %>
      <%= sample.number_field :molybdate, {class: 'form-control', step: 'any', placeholder: 'Molybdate'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :silicate, "Silicate (as ppm SiO2)" %>
      <%= sample.number_field :silicate, {class: 'form-control', step: 'any', placeholder: 'Silicate'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :boron, "Boron (as ppm B)" %>
      <%= sample.number_field :boron, {class: 'form-control', step: 'any', placeholder: 'Boron'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :aluminum, "Aluminum (as ppm Al)" %>
      <%= sample.number_field :aluminum, {class: 'form-control', step: 'any', placeholder: 'Aluminum'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :sulfer, "Sulfer (as ppm SO4)" %>
      <%= sample.number_field :sulfer, {class: 'form-control', step: 'any', placeholder: 'Sulfer'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :manganese, "Manganese (as ppm Mn)" %>
      <%= sample.number_field :manganese, {class: 'form-control', step: 'any', placeholder: 'Manganese'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :total_hardness, "Total Hardness (as ppm CaCO3)" %>
      <%= sample.number_field :total_hardness, {class: 'form-control', step: 'any', placeholder: 'Total Hardness'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :ortho_po4, "Ortho PO4 (as ppm PO4)" %>
      <%= sample.number_field :ortho_po4, {class: 'form-control', step: 'any', placeholder: 'Ortho PO4'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :azole, "Azole (as ppm TT)" %>
      <%= sample.number_field :azole, {class: 'form-control', step: 'any', placeholder: 'Azole'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :polymer, "Polymer (as FAU)" %>
      <%= sample.number_field :polymer, {class: 'form-control', step: 'any', placeholder: 'Polymer'}  %>
    </div>
    <div class="form-group">
      <%= sample.label :free_chlorine, "Free Chlorine" %>
      <%= sample.number_field :free_chlorine, {class: 'form-control', step: 'any', placeholder: 'Free Chlorine'}  %>
    </div>
    <%= sample.submit class:'btn btn-default' %>
<% end -%>
<script>
    $('#sample_company_id').on('change',null,function(){
        var company = $( "#sample_company_id" ).val();
        $.ajax({
            url: '/towers?company='+ company,
            success: function(data) {
                console.log(data);
                var towerSelect = $('#sample_tower_id');
                towerSelect.html('');
                towerSelect.append('<option value>Select</option>');
                $.each(data, function(key, val){
                    towerSelect.append('<option value="' + val.id + '">' + val.name + '</option>');
                })
            }
        });
    })
    $(document).ready(function(){
        $('.datepicker').datepicker();
    });
</script>

app/views/samples/edit.html.erb
<h1>Edit Sample Data</h1>
<%= render :partial => 'form' %>

app/views/samples/index.html.erb
<h1>Recorded Samples</h1>

<table border="1">
  <thead>
  <tr>
    <th>Id</th>
    <th>Sample Date</th>
    <th>Company</th>
    <th>Tower</th>
    <th>Options</th>
  </tr>
  </thead>

  <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to sample.id, sample %></td>
        <td><%= sample.sample_date.strftime('%m/%d/%Y') %></td>
        <td><%= sample.company.name %></td>
        <td><%= sample.tower.name %></td>
        <td>
          <%= link_to 'Edit', edit_sample_path(sample.id) %>
          <%= link_to 'Delete', sample, :method => 'delete' %>
        </td>
      </tr>
  <% end -%>
</table>

<p><%= link_to 'New Sample', new_sample_path %></p>

app/views/samples/new.html.erb
<h1>New Data Sample</h1>
<%= render :partial => 'form' %>

app/views/samples/show.html.erb
<h1><%= @sample.id %></h1>

<%= @sample.created_at %>
 <br>
<%= @sample.conductivity %>
 <br>
<a href="/samples/<%= @sample.id %>/edit">Edit</a>               l

app/views/site/index.html.erb
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Your Cooling Tower</title>
  <%= favicon_link_tag 'favicon-flask.ico' %>
  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">YourCoolingTower</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
        </li>
        <li>
          <a class="page-scroll" href="#services">Services</a>
        </li>
        <li>
          <a class="page-scroll" href="#how_it_works">How it Works</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
        <li>
          <% if user_signed_in? %>
              <%= link_to "Dashboard", dashboard_path %>
          <% else %>
              <a href="/users/sign_in">Login</a>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<!-- Header -->
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Insight into your cooling tower's health</div>
      <div class="intro-heading">Your Cooling Tower</div>
      <a href="#services" class="page-scroll btn btn-xl">Learn More</a>
    </div>
  </div>
</header>

<!-- Services Section -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Services</h2>
        <h3 class="section-subheading text-muted">What we provide.</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-bar-chart-o fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">Data & Analysis</h4>
        <p class="text-muted">By sending us periodic water samples from Your Cooling Tower, we will provide you with
          detailed data and analysis reports giving you insight into your Cooling Tower's health in
          the most critical areas.  With this insight you can make more informed decisions on how to budget and spend
          on Your Cooling Tower maintenance.
        </p>
      </div>
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-dollar fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">Solutions</h4>
        <p class="text-muted">Depending on Your Cooling Tower's health we will provide recommendations on the treatments you
          need in order to keep Your Cooling Tower running in the most optimal fashion.  We can also provide the chemicals
          you need to treat Your Cooling Tower so that you can apply them and save greatly on Your Cooling Tower maintenance
          expenses.</p>
      </div>
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">Online & Secure</h4>
        <p class="text-muted">Data and analysis reports for Your Cooling Tower are always available at
          YourCoolingTower.com using your secure login.  Your Cooling Tower data is viewable only by you and is
          safely backed-up and maintained in our databases. Your Cooling Tower data is always viewable using our
          state of the art query and reporting technologies</p>
      </div>
    </div>
  </div>
</section>

<!-- How it works Section -->
<section id="how_it_works">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">How it Works</h2>
        <h3 class="section-subheading text-muted">How we provide insight.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline">
          <li>
            <div class="timeline-image">
              <%= image_tag("1.jpg", :class => "img-circle img-responsive", :alt => "step 1" ) %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Step #1</h4>
                <h4 class="subheading">We send you an analysis packet</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">After signing up with us, we will periodically send you sample packets which include
                  sample bottles, labels and pre-marked shipping materials.</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <%= image_tag("2.jpg", :class => "img-circle img-responsive", :alt => "step 2" ) %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Step #2</h4>
                <h4 class="subheading">You send us water samples</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Using the sample packet that we provide, you will periodically take samples of
                  the water from Your Cooling Tower and send those samples to our lab for testing.</p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-image">
              <%= image_tag("3.jpg", :class => "img-circle img-responsive", :alt => "step 3" ) %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Step #3</h4>
                <h4 class="subheading">We provide detailed data, analysis and recommendations</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">At our labs we will analyze the sample, record the results into our
                  database and generate sophisticated reports which you can access online using your
                  secure login.</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <%= image_tag("4.jpg", :class => "img-circle img-responsive", :alt => "step 4" ) %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Step #4</h4>
                <h4 class="subheading">Use the data as you see fit</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">You can use the data to observe trends in Your Cooling Tower over time which
                can help you make informed maintenance decisions.  Additionally, we can make recommendations and
                provide you with the chemicals you need to treat Your Cooling Tower saving you money.</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <h4>Healthy
                <br>Cooling
                <br>Tower</h4>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Contact Us</h2>
        <h3 class="section-subheading text-muted">Questions?  Drop us a message.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 text-center">
              <div id="success"></div>
              <button type="submit" class="btn btn-xl">Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Your Cooling Tower 2015</span>
      </div>
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li><a href="#">Privacy Policy</a>
          </li>
          <li><a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
</body>
</html>
<%= javascript_include_tag "application" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>